export const HOSTING_BENEFIT = ['Solusi PHP untuk performa query yang lebih cepat', 'Konsumsi memory yang lebih rendah', 'Support PHP 5.3, PHP 5.4, PHP 5.5, PHP 7', 'Fitur enkripsi IonCube dan Zend Guard Loaders']
export const HOSTING_PRICE = [
  {
    name: 'Bayi',
    normalPrice: 19900,
    realPrice: 14900,
    users: 938,
    diskSpace: 500,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: false,
    domainAddon: null,
    privateNameServer: false,
    spam: null,
    resourcePower: 0.5,
    popEmail: null,
    backup: null
  },
  {
    name: 'Pelajar',
    normalPrice: 46900,
    realPrice: 23450,
    users: 938,
    diskSpace: null,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: true,
    domainAddon: null,
    privateNameServer: false,
    spam: null,
    resourcePower: 1,
    popEmail: 'unlimited',
    backup: null
  },
  {
    name: 'Personal',
    normalPrice: 58900,
    realPrice: 38900,
    users: 938,
    diskSpace: null,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: true,
    domainAddon: 'unlimited',
    privateNameServer: true,
    spam: 'SpamAssasin Mail',
    resourcePower: 2,
    popEmail: 'unlimited',
    backup: 'instant',
    isBestSeller: true
  },
  {
    name: 'Bisnis',
    normalPrice: 109000,
    realPrice: 65900,
    users: 938,
    diskSpace: null,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: true,
    domainAddon: 'unlimited',
    privateNameServer: true,
    spam: 'SpamExpert Pro',
    resourcePower: 3,
    popEmail: 'unlimited',
    backup: 'magic auto'
  }
]
export const PHP_RUNNING = [
  'IcePHP',
  'http',
  'nd_pdo_mysql',
  'stats',
  'apc',
  'huffman',
  'oauth',
  'stem',
  'apcu',
  'idn',
  'oci8',
  'stomp',
  'apm',
  'igbinary',
  'odcb',
  'suhosin',
  'ares',
  'imagick',
  'opcache',
  'sybase_ct',
  'bcmath',
  'imap',
  'pdf',
  'sysvmsg',
  'bcompiler',
  'inclued',
  'pdo',
  'sysvsem',
  'bif_int',
  'inotify',
  'pdo_dblib',
  'sysvshm',
  'bitset',
  'interbase',
  'pdo_firebird',
  'tidy',
  'bloomy',
  'intl',
  'pdo_mysql',
  'timezonedb',
  'bz2_filter',
  'ioncube_loader',
  'pdo_odbc',
  'trader',
  'clamav',
  'ioncube_loader_4',
  'pdo_pgsql',
  'translit',
  'coin_acceptor',
  'jsmin',
  'pdo_sqlite',
  'uploadprogress',
  'crack',
  'json',
  'pgsql',
  'uri_template',
  'dba',
  'Idap',
  'phalcon',
  'uuid'
]

export const POWERFUL_LIST = [
  'max execution time 300s',
  'post max size 128 MB',
  'max execution time 300s',
  'upload max file size 128MB',
  'PHP memory limit 1024 MB',
  'max input vars 2500'
]
