export const HOSTING_BENEFIT = ['Solusi PHP untuk performa query yang lebih cepat', 'Konsumsi memory yang lebih rendah', 'Support PHP 5.3, PHP 5.4, PHP 5.5, PHP 7', 'Fitur enkripsi IonCube dan Zend Guard Loaders']
export const HOSTING_PRICE = [
  {
    name: 'Bayi',
    normalPrice: 19900,
    realPrice: 14900,
    users: 938,
    diskSpace: 500,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: false,
    domainAddon: null,
    privateNameServer: true,
    spamAssasin: true
  },
  {
    name: 'Pelajar',
    normalPrice: 19900,
    realPrice: 14900,
    users: 938,
    diskSpace: 500,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: false,
    domainAddon: null,
    privateNameServer: true,
    spamAssasin: true
  },
  {
    name: 'Personal',
    normalPrice: 19.9,
    realPrice: 14.9,
    users: 938,
    diskSpace: 500,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: false,
    domainAddon: null,
    privateNameServer: true,
    spamAssasin: true
  },
  {
    name: 'Bisnis',
    normalPrice: 19.9,
    realPrice: 14.9,
    users: 938,
    diskSpace: 500,
    bandwidth: 'unlimited',
    database: 'unlimited',
    domain: 1,
    instantBackup: true,
    unlimitedSSL: true,
    freeDomain: false,
    domainAddon: null,
    privateNameServer: true,
    spamAssasin: true
  }
]
